<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="css/estilos.css">
    <title>Héctor Pascual Marín</title>
    
</head>
<body>
    <header>
        <nav>
            <img src="imagenes/logo.jpg" alt="Librería DAW" class="logo-width">
            <ul class="navbar">                
                <li><a href="index.php">Inicio</a></li>
                <li><a href="alta_libros.php">Alta de libros</a></li>
            </ul>
        </nav> 
    </header>
